#!/bin/bash
if [ -z "$PYFILE" ]; then
    echo "PYFILE environment variable is not set."
    exit 1
fi
# Check if the specified Python file exists
if [ ! -f "$PYFILE" ]; then
    echo "Python file $PYFILE does not exist."
    exit 1
fi
# Compile the Python script using the "compileall" module
python3 -m compileall "$PYFILE" -b
if [ $? -eq 0 ]; then
    echo "Compiling $PYFILE ..."
    compiled_filename="${PYFILE}c"
    echo "Compilation successful. Compiled files can be found in the '__pycache__' directory."
else
    echo "Compilation failed."
fi
